global:
  scrape_interval: 1s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    # static_configs:
      # - targets: ['node-exporter:9100']
    dns_sd_configs:
      - names:
        - 'tasks.node-exporter'
        type: 'A'
        port: 9100
  - job_name: 'cadvisor'
    # static_configs:
      # - targets: ['cadvisor:8080']
    dns_sd_configs:
      - names:
        - 'tasks.cadvisor'
        type: 'A'
        port: 8080
  - job_name: 'cassandra-jmx'
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets:
          - '192.168.1.12:7070'
          - '192.168.1.13:7070'
          - '192.168.1.14:7070'
          - '192.168.1.15:7070'
          - '192.168.1.16:7070'
        labels:
          service: cassandra-jmx