global:
  scrape_interval: 1s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    # static_configs:
      # - targets: ['node-exporter:9100']
    dns_sd_configs:
      - names:
        - 'tasks.node-exporter'
        type: 'A'
        port: 9100
  - job_name: 'cadvisor'
    # static_configs:
      # - targets: ['cadvisor:8080']
    dns_sd_configs:
      - names:
        - 'tasks.cadvisor'
        type: 'A'
        port: 8080
  - job_name: 'cassandra-jmx'
    metrics_path: /metrics
    metrics_path: /metrics
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      # keep only services that have label monitor="cassandra"
      - source_labels: [__meta_dockerswarm_service_name]
        regex: cl_cassandra_cassandra-.*
        action: keep

      # Store node IP into a temporary label
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __tmp_node_ip__

      # Finally overwrite __address__ as the LAST step
      - source_labels: [__tmp_node_ip__]
        target_label: __address__
        replacement: '$1:7070'
        action: replace